global:
  scrape_interval: 2s
  external_labels:
    monitor: 'medioambiente_delicias'
    app: 'prometheus.delicias-p5'

# Reglas que hay que ejecutar al recibir métricas de la fuente de datos. 
# Son el cálculo del valor medio de temperatura y humedad.
rule_files:
  - 'delicias.rules'

scrape_configs:
  - job_name: 'delicias'  # No es relevate ya que que honor_labels es true.
    static_configs:
      - targets: ['np-pushgateway-delicias.delicias-p5:12345']
    honor_labels: true
    honor_timestamps: true


alerting:
  alertmanagers:
    - static_configs:
      - targets: ['np-alertmanager.madrid-p5:8888']