version: '3'
services:
  grafana:
    image: grafana/grafana
    user: '0'
    network_mode: 'host'
    volumes:
      - ./grafana_db:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=CompNub-P5-YAGO